site_name: Aprendizado Coletivo Python
site_description: Construção coletiva de conhecimentos sobre Python, desenvolvimento e tecnologia.
site_url: https://devleonardoamaral.github.io/aprendizado-coletivo-python/
repo_name: GitHub
docs_dir: articles
repo_url: https://github.com/devleonardoamaral/aprendizado-coletivo-python/
use_directory_urls: true

theme:
  name: material
  language: pt-BR
  custom_dir: overrides
  logo: images/logo.png
  favicon: images/favicon.ico
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
  palette:
    # dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: yellow
      accent: deep purple
    # light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Página Inicial: index.md
  - Python:
      - Fundamentos:
          - Tipos Primitivos: python/fundamentos/tipos_primitivos.md
  - Sobre o Projeto: about.md

plugins:
  - meta
  - search
