authors:
  leonardo_amaral:
    name: Leonardo Amaral
    description: Software Developer
    avatar: https://avatars.githubusercontent.com/u/94996150?v=4
    slug: 94996150?v=4
    url: https://github.com/devleonardoamaral
  fernando_santini:
    name: Fernando Santini
    description: Software Developer
    avatar: https://avatars.githubusercontent.com/u/15256430?v=4
    slug: 15256430?v=4
    url: https://github.com/OSX-RSPlug-a
